#! /bin/sh
# servers to check.   (Separate multiple servers with spaces.)
#NTPSERVERS="pool.ntp.org"
#NTPSERVERS="141.40.103.103 141.82.49.102"
#
# additional options for ntpdate
#NTPOPTIONS="-v"
#NTPOPTIONS="-ub"

# CMD:
#/usr/sbin/ntpdate -us 141.40.103.103 91.189.94.4
/usr/sbin/ntpdate -us atom.uhr.de pool.ntp.org
#/sbin/hwclock --systohc
