#! /bin/bash
#deb
#rh
#gentoo

##DEBUG
#set -x

## VAR
RSCMAXSSD=0
RSCMAXHDD=5

DATE="`date '+%Y%m%d%H%M'`"
TMPF="/tmp/disk-health_$DATE"
DISKS="/tmp/disk-health_disks_$DATE"
## check for smartmontools installed

if [ ! -e /usr/sbin/smartctl ]; then
	echo "SMART Mon Tools not installed"
	exit 1	
fi

## check at dmesg
cat /var/log/dmesg |grep -i -E "drbd|ata|scsi|ide" |grep -i -E "fail|error|fault">> $TMPF

## search useable disks
/usr/sbin/smartctl --scan |cut -d " " -f 1 > $DISKS

## check smart

while read line
do
    name=$line
	sline=$(echo $line |cut -d "/" -f 3)
	DISKTYPE=$(cat /sys/block/$sline/queue/rotational)
	smartctl -H -q errorsonly $line  >> $TMPF
	# SSD
	if [ $DISKTYPE = 0 ]; then
	RSCMAX="$RSCMAXSSD"
	RSC=$(smartctl -a $line |grep "Reallocated_Event_Count" | cut -d " " -f 32)	
	## HDD
	else
	RSCMAX="$RSCMAXHDD"
	RSC=$(smartctl -a $line |grep "Reallocated_Sector_Ct" | cut -d " " -f 36)
	fi
	## beides
	if [ $RSC -gt $RSCMAX ]; then
		echo "Warning: $line Reallocated Sectors/Events is greater than Limit ($RSCMAX): $RSC" >> $TMPF
	fi
	
done < $DISKS

cat $TMPF


rm $DISKS
rm $TMPF
