#!/bin/sh

#set -x

if [ "$(cat /proc/drbd |grep cs: |grep -v 'UpToDate/UpToDate')" != "" ]; then
	echo "One or more drbd-disks has errors:" > /tmp/drbd-check.log
	cat /proc/drbd |grep cs: |grep -v 'UpToDate/UpToDate'>> /tmp/drbd-check.log
	echo "" >> /tmp/drbd-check.log
	echo "================COMPLETE-LOG================" >> /tmp/drbd-check.log
	cat /proc/drbd >> /tmp/drbd-check.log
	dmesg -T|grep -i drbd >> /tmp/drbd-check.log
	cat /tmp/drbd-check.log |mail -s "$(hostname): DRBD-Check Warning" paladin@pilarkto.net
	rm /tmp/drbd-check.log
fi
