#! /bin/bash

#PvSA, 11.6.11
# Zeigt die aktiven aktullen Netzwerkverbindungen an, ohne localhost
# for different user (not just root)
# jetzt auch fuer Mac (Darwin Kernel)

#DEBUG
#set -x

if [ "$1" = "-h" ] || [ "$#" -lt "1" ]; then
        echo " netwatch [-u/-t/-h] [-l]: netstat shortcuts for Linux and Mac-Darwin"
        echo "  -u: UDP, -t: TCP"
        echo "  -h: help"
        echo "  -l: Listening Sockets"
        exit 0
fi



if [ "`uname`" = "Darwin" ]; then
        OPT1="-an"
        if [ "$1" = "-t" ]; then
                OPT2="-p tcp"
        else
                OPT2="-p udp"
        fi
        if [ "$2" = "-l" ];then
                if [ "$1" = "-u" ];then
                        netstat $OPT1 $OPT2
                else
                        netstat $OPT1 $OPT2 |grep -i 'LISTEN'
                fi
        else
                netstat $OPT1 $OPT2 |egrep -i 'EST|VERB' |grep -v 127.0.0.1
        fi

else
        WHO=`whoami`
        if [ "$WHO" = "root" ];then
                OPT1="-anp"
        else
                OPT1="-an"
        fi
        if [ "$1" = "-t" ]; then
                OPT2="-t"
        else
                OPT2="-u"
        fi
        if [ "$2" = "-l" ];then
                if [ "$1" = "-u" ];then
                        netstat $OPT1 $OPT2
                else
                        netstat $OPT1 $OPT2 |grep -i 'LISTEN'
                fi
        else
                watch "netstat $OPT1 $OPT2 |grep -i 'EST|VERB' |grep -v 127.0.0.1"
        fi
fi

