#! /bin/bash
## v.1 PvSA, 8.11.09
## v.1.1 PvSA 30.9.2010
## v.1.2 PvSA, 16.1.2011: Bug Dir-Support, loeschen von "/" am Ende
##v.1.3 PvSA, 20.7.11: Check for Updates


## VARS
VON=`echo "$1" | sed -e 's,/$,,' `
#NACH=$2
USER=`whoami`
DATE=`date '+%Y%m%d-%H_%M'` 
STORE=/var/backups/pbackup
STORE_NEW=$STORE/$USER-$DATE


## HELP ?
if [ "$1" = "-h" ];then 
	echo "PILARKTO.NET Backup Skript - Root-Only Version 1.1"
	echo "pbackup [file or folder]"
	echo "Example: pbackup /etc/postfix (without last "/")"
	echo "no wildcards "*" etc are supporetd"
	exit 0
fi
if [ "$1" = "" ];then
	echo "not enough parameters, try pbackup -h for help"
	exit 1
fi



## PBACKUP
echo "Backing up now: "$VON" ..."

# make folders (even base if not exist)
mkdir -p $STORE_NEW

# symbolic link ?
if [ -L "$VON" ];then
	echo "Attention: This is a symbolic link and this is probably not what you want !!"
	DODIFF="no"
fi

# Size greater than zero
if [ ! -s "$VON" ];then
	echo "Atention: The file size is 0 Byte !!"
	DODIFF="no"
fi

# Copy to Backups
cp -a "$VON" $STORE_NEW/
chmod 500 $STORE_NEW
BAKTGT=$STORE_NEW/`ls $STORE_NEW`
echo "Folder/File copied to $BAKTGT"

# Compare to original
if [ "$DODIFF" != "no" ]; then
	# Testing Backuo
	diff -qry $VON $BAKTGT
	echo "-------------------------------------------------------------" 
	if [ "$?" = "0" ];then
		echo "FINISH: Backup machtes PERFECTLY to origin !"
	else
		echo "FINISH: Backup NOT machting to origin, see output above !"
	fi
else
	echo "Not comparing, because it make no sense (see above)"
fi
