#! /bin/bash
## Script for check up if pnet-suite has changed/local repo is in sync

##DEBUG
#set -x

##VAR
LOCDIR="/usr/share/pnet-suite"
TMPF="/tmp/chkout_`date +'%Y%m%d%H%M'`"
PAL="root"

##PROGRAM
if [ -d  "$LOCDIR" ]; then
	cd $LOCDIR
	git checkout > $TMPF
	if [ "`cat $TMPF`" != "" ] || [ "`cat $TMPF`" != "Your branch is up-to-date with 'origin/master'." ] ; then
	# do something
		cat $TMPF |mail -s "`hostname -f`: pnet-suite repo-check" $PAL
		rm $TMPF
	#else do nothing/keep quite
	fi

else
	exit 1
fi
