#! /bin/sh
## Script to renew letsencrypt certs of nginx

##DEBUG
#set -x

##PROGRAM
service nginx stop  # or whatever your webserver is
certbot renew --standalone > /var/log/letsencrypt/renew.log 2>&1
LE_STATUS=$?
service nginx start # or whatever your webserver is
if [ "$LE_STATUS" != 0 ]; then
    echo Automated renewal failed:
    cat /var/log/letsencrypt/renew.log
    exit 1
fi

