#! /bin/sh
# PvSA, 2011 (Init)
# PvSA, 19.11.2012:
## - nur Mail schicken, wenn neue Pakete
## - Warnen, wenn yum und apt installiert sind
# PvSA, 30.11.2013 - gentoo support 

## DEBUG
#set -x

## CHANGE THIS TO REAL MAILADRESS ##
PAL="root"

##
SERVER="`hostname`"

## create tmp-file
touch /tmp/update-check.log

## Wenn apt und yum, dann warnungsmail senden
if [ -e /etc/apt/sources.list ] && [ -e /etc/yum.conf ] && [ -e /etc/gentoo-release ]; then
        echo "Warning: System hat apt und yum als Paketmanager installiert. Nicht klar, welcher verwendet werden soll" >> /tmp/update-check.log

# wenn nur apt
elif [ -e /etc/apt/sources.list ]; then
        apt-get -qq update
        #apt-get -suV upgrade >> /tmp/update-check.log
        apt-get -qqsuV upgrade >> /tmp/update-check.log

# wenn nur yum
elif [ -e /etc/yum.conf ];then
        yum -q check-update >> /tmp/update-check.log
elif [ -e /usr/sbin/emerge ] || [ /usr/bin/emerge ];then
	#Update Portage
	emerge --sync -q &> /dev/null
	if [ $? -ne 0 ]; then
		echo "Portage Update failed - Trying again without quiet option"
		emerge --sync
	fi
	#Vulnerability Check
        if [ -e /usr/bin/glsa-check ]; then
                GLSA="`glsa-check -q -t affected 2>/dev/null`"
                if [ "$GLSA" != "" ] || [ $? != 0 ] ;then
                glsa-check -p -n affected >> /tmp/update-check.log
                fi
                ## else here means, there are no affected GLSAs
        else
                echo 'Gentoo system, but no gentoolkit installed' |mail -s "$SERVER: Ausstehende Updates" $PAL
        fi
fi

# Mail nur senden, wenn nicht leer
if [ "`cat /tmp/update-check.log`" != "" ]; then
        cat /tmp/update-check.log| mail -s "$SERVER: Ausstehende Updates" $PAL
fi

# log-file loeschen
rm -f /tmp/update-check.log

