#! /bin/sh
# PvSA, 2011 (Init)
# PvSA, 19.11.2012:
## - nur Mail schicken, wenn neue Pakete
## - Warnen, wenn yum und apt installiert sind
# PvSA, 30.11.2013 - gentoo support 
# PvSA, 19.2.18 - optimize debian/ubuntu mail layout

## DEBUG
#set -x

## CHANGE THIS TO REAL MAILADRESS ##
PAL="root@localhost"

##
SERVER="`hostname`"
LOG="/tmp/update-check.log"

## create tmp-file
touch $LOG

## Wenn apt und yum, dann warnungsmail senden
if [ -e /etc/apt/sources.list ] && [ -e /etc/yum.conf ] && [ -e /etc/gentoo-release ]; then
        echo "Warning: System hat apt und yum als Paketmanager installiert. Nicht klar, welcher verwendet werden soll" >> /tmp/update-check.log

# wenn nur apt
elif [ -e /etc/apt/sources.list ]; then
        apt-get -qq update
	if [ "`apt-get dist-upgrade -s | grep -i security`" != "" ]; then
        echo "Updates available for Debian/Ubuntu version: `cat /etc/debian_version` \n" >> $LOG
        #echo "" >> $LOG
        echo "================ `date` ====================== \n" >> $LOG
        #echo "n" | apt-get dist-upgrade |grep -v '/n\]'| sed '1,3d' >> $LOG
        #echo "" >> $LOG
        apt-get -V -s dist-upgrade     |grep -E "^   .*=>.*"     |awk 'BEGIN {
        ul=sprintf("%*s",40,""); gsub(/ /,"-",ul);
        printf "%-30s %-30s %-30s\n", "Package", "Installed", "Available";
        printf "%-30.30s %-30.30s %-30.30s\n", ul, ul, ul;
     }
     {
        printf "%-30s %-30s %-30s\n",
               $1,
               substr($2,2),
               substr($4,1,length($4)-1)
     }' >> $LOG
	echo "" >> $LOG
	echo "paket infos in detail:" >> $LOG
        echo "========================================================" >> $LOG
        aptitude search '~U' >> $LOG
        echo "--------------------------------------------------------" >> $LOG
        echo "For details of the status and falgs see:" >> $LOG
        echo " https://aptitude.alioth.debian.org/doc/en/ch02s02s02.html" >> $LOG
	fi

# wenn nur yum
elif [ -e /etc/yum.conf ];then
        yum -q check-update >> $LOG
elif [ -e /usr/sbin/emerge ] || [ /usr/bin/emerge ];then
	#Update Portage
	emerge --sync -q &> /dev/null
	if [ $? -ne 0 ]; then
		echo "Portage Update failed - Trying again without quiet option"
		emerge --sync
	fi
        which eix-update 2>/dev/null 1>/dev/null
        if [ $? -eq 0 ]; then
           eix-update -q
      	fi
	#Vulnerability Check
        if [ -e /usr/bin/glsa-check ]; then
                GLSA="`glsa-check -q -t affected 2>/dev/null`"
                if [ "$GLSA" != "" ] || [ $? != 0 ] ;then
                glsa-check -p -n affected >> $LOG
                fi
                ## else here means, there are no affected GLSAs
        else
                echo 'Gentoo system, but no gentoolkit installed' |mail -s "$SERVER: Ausstehende Updates" $PAL
        fi
fi

# Mail nur senden, wenn nicht leer
if [ "`cat $LOG `" != "" ]; then
        cat $LOG| mail -s "$SERVER: Ausstehende Updates" $PAL
fi

# log-file loeschen
rm -f $LOG

